environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86_64
      PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: "64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86_64
      PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: "64"

build: off

install:
  - ps: |
      $ErrorActionPreference = "Continue"
      $env:PATH = "$env:PYTHON\Scripts\;$env:PATH"
      echo "$env:PATH"
      dir "$env:PYTHON\Scripts\"
      python --version
      pip --version
      pip --disable-pip-version-check install poetry
      poetry install

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      poetry run invoke lint
      poetry run invoke test
