environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      ARCH: x86_64
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "32"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH: x86_64
      PYTHON: "C:\\Python36"
      PYTHON_ARCH: "64"

install:
  - set PATH=%PYTHON%/Scripts/;%PATH%
  - ps: |
      $ErrorActionPreference = "Continue"
      dir "%PYTHON%/Scripts/"
      python.exe --version
      pip.exe --version
      pip.exe --disable-pip-version-check install poetry
      poetry install

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      poetry run invoke lint
      poetry run invoke test
