environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - ps: |
      $ErrorActionPreference = "Stop"
      pip.exe --disable-pip-version-check install poetry
      poetry install

test_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      poetry run invoke lint
      poetry run invoke test
