language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6-dev
    - os: linux
      dist: xenial
      python: 3.7-dev
    - os: linux
      dist: xenial
      python: 3.8-dev
    - os: osx
      osx_image: xcode10.2
      script: python --version
    - os: osx
      osx_image: xcode10.1
      script: python --version
    - os: osx
      osx_image: xcode10
      script: python --version
    - os: osx
      osx_image: xcode9.4
      script: python --version
    - os: osx
      osx_image: xcode9.3
      script: python --version
    - os: osx
      osx_image: xcode9.2
      script: python --version
    - os: osx
      osx_image: xcode9.1
      script: python --version
    - os: osx
      osx_image: xcode9
      script: python --version
    - os: osx
      osx_image: xcode8.3
      script: python --version
    - os: osx
      osx_image: xcode8
      script: python --version

install:
  - pip install poetry
  - poetry install

script:
  - poetry run make lint
  - poetry run make test
