language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6-dev
    - os: linux
      dist: xenial
      python: 3.7-dev
    - os: linux
      dist: xenial
      python: 3.8-dev
    - os: osx
      python: 3.6-dev
    - os: osx
      python: 3.7-dev
    - os: osx
      python: 3.8-dev

install:
  - pip install poetry
  - poetry install

script:
  - poetry run make lint
  - poetry run make test
