language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.6-dev
    - os: linux
      dist: xenial
      python: 3.7-dev
    - os: linux
      dist: xenial
      python: 3.8-dev
    - os: osx
      osx_image: xcode10.2
      # `language: python` tries to install Python, which fails on OSX.
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode10.1
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode10
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode9.4
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode9.3
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode9.2
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode9.1
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode9
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode8.3
      language: shell
      install:
      script: python --version
    - os: osx
      osx_image: xcode8
      language: shell
      install:
      script: python --version

install:
  - pip install poetry
  - poetry install

script:
  - poetry run make lint
  - poetry run make test
