name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        python: [3.6, 3.7]
        os: [ubuntu, macOS, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}-dev
    - name: Install dependencies
      env:
        POETRYENV: ${{ matrix.python }}
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        export PATH=$HOME/.poetry/bin:$PATH
        poetry install
    - name: Lint
      run: poetry run invoke lint
    - name: Test
      run: poetry run invoke test
