name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
        os: [ubuntu, macOS, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint
      run: poetry run invoke lint
    - name: Test
      run: poetry run invoke test
